# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (12 hours)
  schedule: [{cron: "0 12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["ItzMe"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: HemantSachdeva
          template: classic
          base: header, activity, repositories, metadata
          commits_authoring: Hemant Sachdeva, hemant.evolver@gmail.com
          committer_branch: dumps
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 20
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_notable_from: organization
          repositories: 200
          repositories_batch: 200
          repositories_forks: yes
